## 12.1 R矩阵

In [ ]:
A <- matrix(11: 16, nrow=3, ncol=2)
print(A)


In [6]:
# nrow 行数 ncol 列数，向量元素填入次序默认是按列填入，用byrow
B <- matrix(c(1, -1, 1, 1), nrow = 2, ncol = 2, byrow = TRUE)
print(B)

     [,1] [,2]
[1,]    1   -1
[2,]    1    1


## 12.2 矩阵子集

In [10]:
A[1,]
A[1,1]
A[, 1]
A[c(1, 3), 1:2]


[1] 11 14

[1] 11

[1] 11 12 13

[,1] [,2]
[1,] 11   14  
[2,] 13   16

In [15]:
# colnames() 函数可以给矩阵每列命名，也可以访问矩阵名，用rownames()函数可以给矩阵每行命名，也可以访问矩阵行名
colnames(A) <- c("A", "B")
A

A  B 
[1,] 11 14
[2,] 12 15
[3,] 13 16

In [ ]:
# cbind(x)
# x为矩阵，将矩阵变为列向量
# cbind(x,y,z) 如果xyz为等长向量，则组成矩阵


# rbind(x) 
# x为矩阵，则将矩阵变成行向量



## 12.4 矩阵运算

### 12.4.1 四则运算

In [20]:
c1 <- A +2
c1
c2 <- A /2
c2
c1 * A
c2 / A

A  B 
[1,] 13 16
[2,] 14 17
[3,] 15 18

A   B  
[1,] 5.5 7.0
[2,] 6.0 7.5
[3,] 6.5 8.0

A   B  
[1,] 143 224
[2,] 168 255
[3,] 195 288

A   B  
[1,] 0.5 0.5
[2,] 0.5 0.5
[3,] 0.5 0.5

### 12.4.2 矩阵乘法

In [26]:
A %*% B

[,1] [,2]
[1,] 25   3   
[2,] 27   3   
[3,] 29   3

### 12.4.3 向量与矩阵相乘

In [24]:
B

[,1] [,2]
[1,] 1    -1  
[2,] 1     1

In [25]:
c(1, 1) %*% B

[,1] [,2]
[1,] 2    0

In [27]:
B %*% c(1, 1)

[,1]
[1,] 0   
[2,] 2

In [28]:
c(1, 1) %*% B %*% c(1, 1)

[,1]
[1,] 2

### 12.4.4 内积

In [33]:
A
# 内积
crossprod(A)

A  B 
[1,] 11 14
[2,] 12 15
[3,] 13 16

A   B  
A 434 542
B 542 677

### 12.4.5 外积

In [34]:
c(1, 2, 3) %o% c(1, -1)

[,1] [,2]
[1,] 1    -1  
[2,] 2    -2  
[3,] 3    -3

## 12.5 逆矩阵与线性方程组求解

In [ ]:
# 逆矩阵
solve(B)
solve(A, c(1,2))

## 12.6 apply() 函数

In [42]:

# apply(A, 2, FUN) 将矩阵A的每一列分别输入到函数FUN中，返回对应于每一列的结果
D <- matrix(c(6, 2, 3, 5, 4, 1), nrow = 3, ncol = 2)
D
apply(D, 2, sum)

[,1] [,2]
[1,] 6    5   
[2,] 2    4   
[3,] 3    1

[1] 11 10

## 12.7 多维矩阵

In [39]:
ara <- array(1:24, dim = c(2, 3, 4))
ara
ara[,,2]
ara[,2:3,2]

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24

[,1] [,2] [,3]
[1,] 7     9   11  
[2,] 8    10   12

[,1] [,2]
[1,]  9   11  
[2,] 10   12